project:
  type: website
lang: es
website:
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog_index.qmd
      - about.qmd
      
format:
  html:
    theme: 
      - cosmo
      - styles.scss
    css: styles.scss
    toc: true
about:
  template: marquee
